# --- src/coreason_etl_hpo/silver.py ---

import polars as pl

from coreason_etl_hpo.identity import generate_coreason_id

# Constants
HP_ID_REGEX = r"^HP:\d{7}$"


def _validate_and_drop_original_id(df: pl.DataFrame, target_col: str, original_col: str) -> pl.DataFrame:
    """
    Validates that the target HP ID column conforms to the HP_ID_REGEX and is not null.
    Raises a ValueError exposing the original invalid ID if validation fails.
    Drops the original ID column upon success.
    """
    invalid_ids = df.filter(pl.col(target_col).is_null() | ~pl.col(target_col).str.contains(HP_ID_REGEX))
    if not invalid_ids.is_empty():
        raise ValueError(f"Found invalid {target_col} entries: {invalid_ids[original_col].to_list()}")
    return df.drop([original_col])


def transform_silver_nodes(
    bronze_df: pl.LazyFrame | pl.DataFrame,
    synonyms_df: pl.LazyFrame | pl.DataFrame | None = None,
    edges_df: pl.LazyFrame | pl.DataFrame | None = None,
) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_nodes data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_nodes table).
        synonyms_df: The nested synonyms dataframe generated by dlt.
        edges_df: The edges dataframe to determine parent hierarchy.

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO concepts.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

    available_cols = lazy_df.collect_schema().names()

    # Determine column names based on potential flattening
    def_col: str | None = (
        "meta__definition__val" if "meta__definition__val" in available_cols else "meta_definition_val"
    )
    if def_col not in available_cols:
        def_col = None

    dep_col: str | None = "meta__deprecated" if "meta__deprecated" in available_cols else "meta_deprecated"
    if dep_col not in available_cols:
        dep_col = None

<<<<<<< HEAD
    # Determine type column name
    type_col: str | None = "type" if "type" in available_cols else None
=======
    # Determine synonym column
    syn_col: str | None = "meta__synonyms" if "meta__synonyms" in available_cols else "meta_synonyms"
    if syn_col not in available_cols:
        syn_col = None
>>>>>>> 68b9210 (validation changes implemented)

    select_exprs = [
        pl.col("id").str.extract(r"(HP[_:]\d+)").str.replace("_", ":").alias("hp_id"),
        pl.col("lbl").str.strip_chars().alias("phenotype_name"),
        pl.col("id"),
        pl.col("_dlt_id"),
    ]

    if type_col:
        select_exprs.append(pl.col(type_col))
    else:
        select_exprs.append(pl.lit(None, dtype=pl.String).alias("type"))

    if def_col:
        select_exprs.append(pl.col(def_col).alias("definition"))
    else:
        select_exprs.append(pl.lit(None, dtype=pl.String).alias("definition"))

    if dep_col:
        select_exprs.append(pl.col(dep_col).fill_null(False).cast(pl.Boolean).alias("is_obsolete"))
    else:
        select_exprs.append(pl.lit(False).alias("is_obsolete"))

    # Append synonym extraction
    if syn_col:
        select_exprs.append(pl.col(syn_col).alias("synonyms"))
    else:
        # Fallback to None if not found
        select_exprs.append(pl.lit(None, dtype=pl.String).alias("synonyms"))

    transformed_df = lazy_df.select(select_exprs).with_columns(
        generate_coreason_id(pl.col("hp_id")).alias("coreason_id")
    )

    if synonyms_df is not None:
        synonyms_lazy = synonyms_df.lazy() if isinstance(synonyms_df, pl.DataFrame) else synonyms_df
        # Expected cols: `val`, `_dlt_parent_id`
        if (
            "val" in synonyms_lazy.collect_schema().names()
            and "_dlt_parent_id" in synonyms_lazy.collect_schema().names()
        ):
            synonyms_agg = synonyms_lazy.group_by("_dlt_parent_id").agg(pl.col("val").str.join("|").alias("synonym"))
            transformed_df = transformed_df.join(synonyms_agg, left_on="_dlt_id", right_on="_dlt_parent_id", how="left")
        else:
            transformed_df = transformed_df.with_columns(pl.lit(None, dtype=pl.String).alias("synonym"))
    else:
        transformed_df = transformed_df.with_columns(pl.lit(None, dtype=pl.String).alias("synonym"))

    if edges_df is not None:
        edges_lazy = edges_df.lazy() if isinstance(edges_df, pl.DataFrame) else edges_df
        if "obj" in edges_lazy.collect_schema().names() and "pred" in edges_lazy.collect_schema().names():
            # A node is a parent if it exists as a target/object in `is_a` or `subClassOf` edges
            parent_ids = (
                edges_lazy.filter(pl.col("pred").str.contains("is_a|subClassOf"))
                .select(pl.col("obj").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("parent_hp_id"))
                .drop_nulls()
                .unique()
                .with_columns(pl.lit(True).alias("is_a_parent"))
            )
            transformed_df = transformed_df.join(
                parent_ids, left_on="hp_id", right_on="parent_hp_id", how="left"
            ).with_columns(pl.col("is_a_parent").fill_null(False))
        else:
            transformed_df = transformed_df.with_columns(pl.lit(False).alias("is_a_parent"))
    else:
        transformed_df = transformed_df.with_columns(pl.lit(False).alias("is_a_parent"))

    transformed_df = transformed_df.drop(["_dlt_id"])

    result_df = transformed_df.collect()

    return _validate_and_drop_original_id(result_df, "hp_id", "id")


def transform_silver_edges(bronze_df: pl.LazyFrame | pl.DataFrame) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_edges data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_edges table).

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO edges.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

    # Extract required columns (sub, pred, obj)
    # Filter for 'is_a' or 'subClassOf' relationships and extract clean HP IDs
    transformed_df = (
        lazy_df.filter(pl.col("pred").str.contains("is_a|subClassOf"))
        .select(
            [
<<<<<<< HEAD
                pl.col("sub").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("source_hp_id"),
                pl.col("obj").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("target_hp_id"),
                pl.col("sub"),
                pl.col("obj"),
=======
                pl.col("sub").str.extract(r"(HP[_:]\d+)").str.replace("_", ":").alias("source_hp_id"),
                pl.col("obj").str.extract(r"(HP[_:]\d+)").str.replace("_", ":").alias("target_hp_id"),
                pl.col("pred"),
>>>>>>> 68b9210 (validation changes implemented)
            ]
        )
        .with_columns(
            [
                generate_coreason_id(pl.col("source_hp_id")).alias("source_coreason_id"),
                generate_coreason_id(pl.col("target_hp_id")).alias("target_coreason_id"),
                # Composite Primary Key for the relationship
                generate_coreason_id(
                    pl.col("source_hp_id") + "_" + pl.col("pred") + "_" + pl.col("target_hp_id")
                ).alias("relationship_coreason_id"),
            ]
        )
    )

    result_df = transformed_df.collect()

    result_df = _validate_and_drop_original_id(result_df, "source_hp_id", "sub")
    return _validate_and_drop_original_id(result_df, "target_hp_id", "obj")


def transform_silver_annotations(bronze_df: pl.LazyFrame | pl.DataFrame) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_annotations data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_annotations table).

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO annotations.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

<<<<<<< HEAD
    # We need to map database_id (e.g., OMIM:619340) and hpo_id (e.g., HP:0011097)
    # The requirement mentions mapping external database identifiers to coreason_id
    # We will generate coreason_id based on hpo_id, and keep database_id

    transformed_df = lazy_df.select(
        [
            pl.col("hpo_id").str.extract(r"(HP:\d+)").alias("hp_id"),
            pl.col("database_id").alias("disease_id"),
            pl.col("disease_name"),
            pl.col("evidence"),
            pl.col("frequency"),
            pl.col("aspect"),
            pl.col("reference"),
            pl.col("onset"),
            pl.col("modifier"),
            pl.col("hpo_id").alias("_original_hpo_id"),
        ]
    ).with_columns(generate_coreason_id(pl.col("hp_id")).alias("coreason_id"))
=======
    transformed_df = (
        lazy_df.select(
            [
                pl.col("hpo_id").str.extract(r"(HP:\d+)").alias("hp_id"),
                pl.col("database_id").alias("disease_id"),
                pl.col("disease_name"),
                pl.col("evidence"),
                pl.col("frequency"),
                pl.col("aspect"),
            ]
        )
        .filter(pl.col("hp_id").is_not_null())
        .with_columns(
            [
                generate_coreason_id(pl.col("hp_id")).alias("coreason_id"),
                # Composite Primary Key for the annotation
                generate_coreason_id(pl.col("disease_id") + "_" + pl.col("hp_id")).alias("annotation_coreason_id"),
            ]
        )
    )
>>>>>>> 68b9210 (validation changes implemented)

    result_df = transformed_df.collect()

    return _validate_and_drop_original_id(result_df, "hp_id", "_original_hpo_id")
