import polars as pl

from coreason_etl_hpo.identity import generate_coreason_id

# Constants
HP_ID_REGEX = r"^HP:\d{7}$"


def transform_silver_nodes(
    bronze_df: pl.LazyFrame | pl.DataFrame,
    synonyms_df: pl.LazyFrame | pl.DataFrame | None = None,
    edges_df: pl.LazyFrame | pl.DataFrame | None = None,
) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_nodes data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_nodes table).
        synonyms_df: The nested synonyms dataframe generated by dlt.
        edges_df: The edges dataframe to determine parent hierarchy.

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO concepts.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

    # Extract required columns and map them to their silver names.
    # We use `.struct.field` if nested, but according to bronze ingestion,
    # native JSON parsing flattens dicts. We will assume columns exist as:
    # id, lbl, meta.definition.val, meta.deprecated
    # Note: DLT might unpack nested fields differently based on configuration.
    # Usually `meta__definition__val`. We need to handle variations.

    # Actually, DLT flattens nested JSON using double underscore by default.
    # So `meta.definition.val` -> `meta__definition__val`
    # `meta.deprecated` -> `meta__deprecated`

    available_cols = lazy_df.collect_schema().names()

    # Determine column names based on potential flattening
    def_col: str | None = (
        "meta__definition__val" if "meta__definition__val" in available_cols else "meta_definition_val"
    )
    if def_col not in available_cols:
        # Fallback if the path is actually different or not present in sample
        def_col = None

    dep_col: str | None = "meta__deprecated" if "meta__deprecated" in available_cols else "meta_deprecated"
    if dep_col not in available_cols:
        dep_col = None

    # Determine type column name
    type_col: str | None = "type" if "type" in available_cols else None

    select_exprs = [
        # Extract HP_1234567 or HP:1234567 and replace the underscore with a colon
        pl.col("id").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("hp_id"),
        pl.col("lbl").str.strip_chars().alias("phenotype_name"),
        pl.col("id"),
        pl.col("_dlt_id"),
    ]

    if type_col:
        select_exprs.append(pl.col(type_col))
    else:
        select_exprs.append(pl.lit(None, dtype=pl.String).alias("type"))

    if def_col:
        select_exprs.append(pl.col(def_col).alias("definition"))
    else:
        select_exprs.append(pl.lit(None, dtype=pl.String).alias("definition"))

    if dep_col:
        select_exprs.append(pl.col(dep_col).fill_null(False).cast(pl.Boolean).alias("is_obsolete"))
    else:
        select_exprs.append(pl.lit(False).alias("is_obsolete"))

    transformed_df = lazy_df.select(select_exprs).with_columns(
        generate_coreason_id(pl.col("hp_id")).alias("coreason_id")
    )

    if synonyms_df is not None:
        synonyms_lazy = synonyms_df.lazy() if isinstance(synonyms_df, pl.DataFrame) else synonyms_df
        # Expected cols: `val`, `_dlt_parent_id`
        if (
            "val" in synonyms_lazy.collect_schema().names()
            and "_dlt_parent_id" in synonyms_lazy.collect_schema().names()
        ):
            synonyms_agg = synonyms_lazy.group_by("_dlt_parent_id").agg(pl.col("val").str.join("|").alias("synonym"))
            transformed_df = transformed_df.join(synonyms_agg, left_on="_dlt_id", right_on="_dlt_parent_id", how="left")
        else:
            transformed_df = transformed_df.with_columns(pl.lit(None, dtype=pl.String).alias("synonym"))
    else:
        transformed_df = transformed_df.with_columns(pl.lit(None, dtype=pl.String).alias("synonym"))

    if edges_df is not None:
        edges_lazy = edges_df.lazy() if isinstance(edges_df, pl.DataFrame) else edges_df
        if "obj" in edges_lazy.collect_schema().names() and "pred" in edges_lazy.collect_schema().names():
            # A node is a parent if it exists as a target/object in `is_a` or `subClassOf` edges
            parent_ids = (
                edges_lazy.filter(pl.col("pred").str.contains("is_a|subClassOf"))
                .select(pl.col("obj").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("parent_hp_id"))
                .drop_nulls()
                .unique()
                .with_columns(pl.lit(True).alias("is_a_parent"))
            )
            transformed_df = transformed_df.join(
                parent_ids, left_on="hp_id", right_on="parent_hp_id", how="left"
            ).with_columns(pl.col("is_a_parent").fill_null(False))
        else:
            transformed_df = transformed_df.with_columns(pl.lit(False).alias("is_a_parent"))
    else:
        transformed_df = transformed_df.with_columns(pl.lit(False).alias("is_a_parent"))

    transformed_df = transformed_df.drop(["_dlt_id"])

    result_df = transformed_df.collect()

    # Validate regex for hp_id
    invalid_ids = result_df.filter(pl.col("hp_id").is_null() | ~pl.col("hp_id").str.contains(HP_ID_REGEX))
    if not invalid_ids.is_empty():
        # Using raw 'id' column to show the original invalid value if 'hp_id' is null
        raise ValueError(f"Found invalid hp_id entries: {invalid_ids['id'].to_list()}")

    return result_df.drop(["id"])


def transform_silver_edges(bronze_df: pl.LazyFrame | pl.DataFrame) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_edges data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_edges table).

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO edges.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

    # Extract required columns (sub, pred, obj)
    # Filter for 'is_a' or 'subClassOf' relationships and extract clean HP IDs
    transformed_df = (
        lazy_df.filter(pl.col("pred").str.contains("is_a|subClassOf"))
        .select(
            [
                pl.col("sub").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("source_hp_id"),
                pl.col("obj").str.extract(r"(HP[_:]\d{7})").str.replace("_", ":").alias("target_hp_id"),
                pl.col("sub"),
                pl.col("obj"),
            ]
        )
        .with_columns(
            [
                generate_coreason_id(pl.col("source_hp_id")).alias("source_coreason_id"),
                generate_coreason_id(pl.col("target_hp_id")).alias("target_coreason_id"),
            ]
        )
    )

    result_df = transformed_df.collect()

    # Validate regex for hp_id
    invalid_sources = result_df.filter(
        pl.col("source_hp_id").is_null() | ~pl.col("source_hp_id").str.contains(HP_ID_REGEX)
    )
    if not invalid_sources.is_empty():
        raise ValueError(f"Found invalid source_hp_id entries: {invalid_sources['sub'].to_list()}")

    invalid_targets = result_df.filter(
        pl.col("target_hp_id").is_null() | ~pl.col("target_hp_id").str.contains(HP_ID_REGEX)
    )
    if not invalid_targets.is_empty():
        raise ValueError(f"Found invalid target_hp_id entries: {invalid_targets['obj'].to_list()}")

    return result_df.drop(["sub", "obj"])


def transform_silver_annotations(bronze_df: pl.LazyFrame | pl.DataFrame) -> pl.DataFrame:
    """
    Transforms the raw bronze_hpo_annotations data into the clean silver layer format.

    Args:
        bronze_df: The input dataframe (e.g., loaded from the bronze_hpo_annotations table).

    Returns:
        A Polars DataFrame matching the silver layer schema for HPO annotations.
    """
    lazy_df = bronze_df.lazy() if isinstance(bronze_df, pl.DataFrame) else bronze_df

    # We need to map database_id (e.g., OMIM:619340) and hpo_id (e.g., HP:0011097)
    # The requirement mentions mapping external database identifiers to coreason_id
    # We will generate coreason_id based on hpo_id, and keep database_id

    transformed_df = lazy_df.select(
        [
            pl.col("hpo_id").str.extract(r"(HP:\d+)").alias("hp_id"),
            pl.col("database_id").alias("disease_id"),
            pl.col("disease_name"),
            pl.col("evidence"),
            pl.col("frequency"),
            pl.col("aspect"),
            pl.col("reference"),
            pl.col("onset"),
            pl.col("modifier"),
            pl.col("hpo_id").alias("_original_hpo_id"),
        ]
    ).with_columns(generate_coreason_id(pl.col("hp_id")).alias("coreason_id"))

    result_df = transformed_df.collect()

    # Validate regex for hp_id
    invalid_hps = result_df.filter(pl.col("hp_id").is_null() | ~pl.col("hp_id").str.contains(HP_ID_REGEX))
    if not invalid_hps.is_empty():
        raise ValueError(f"Found invalid hp_id entries: {invalid_hps['_original_hpo_id'].to_list()}")

    return result_df.drop(["_original_hpo_id"])
